name: Assignment
main: com.github.CubieX.Assignment.Assignment
depend: [Vault]
version: 1.0.6
description: Give out material procurement assignments for a reward 

commands:
    ass:
      description: Using Assignment
      usage: /ass list <PLAYER> | version | reload | cleanup

permissions:

    assignment.make:
        description: Allows creation of an assignment.
        default: op
    assignment.take:
        description: Allows fulfilling an open assignment and gaining of the reward.
        default: op
    assignment.break:
        description: Allows breaking registered Assignment signs that are not your own.
        default: op
    assignment.listother:
        description: Allows listing of other players assignments.
        default: op
    assignment.*:
        description: Allows reloading the plugin and all other commands.
        default: op